- name: Eliminar Chrome
  apt:
    name: "{{ chrome_package }}"
    state: absent
    purge: true


- name: Eliminar dependencias
  apt:
    autoremove: yes
  when: chrome_remove_dependencies


- name: Eliminar repositorio
  apt_repository:
    filename: google-chrome
    repo: "{{ chrome_repo }}"
    state: absent
  when: chrome_remove_repository


- name: Eliminar clave
  file:
    path: "{{ chrome_keyring_dir }}/{{ chrome_keyring_file }}"
    state: absent
  when: chrome_remove_repository


- name: Actualizar cache
  apt:
    update_cache: true
