###############################################################################
# ESTADO
###############################################################################

software_state: present

###############################################################################
# ORIGEN DEL INSTALADOR
###############################################################################

# url | local
freecad_source: url

###############################################################################
# VERSION
###############################################################################

freecad_version: "1.1.1"

###############################################################################
# URL OFICIAL
###############################################################################

freecad_appimage_url: >-
  https://github.com/FreeCAD/FreeCAD/releases/download/{{ freecad_version }}/FreeCAD_{{ freecad_version }}-Linux-x86_64-py311.AppImage

###############################################################################
# REPOSITORIO LOCAL ANSIBLE
###############################################################################

freecad_appimage_local_file: "FreeCAD_{{ freecad_version }}-Linux-x86_64-py311.AppImage"

software_appimage_repository: "{{ playbook_dir }}/../software/software_appimage"

###############################################################################
# INSTALACION
###############################################################################

freecad_install_dir: "/opt/appimages/freecad"

freecad_appimage_file: "FreeCAD.AppImage"

###############################################################################
# ICONO
###############################################################################

freecad_icon_url: "https://wiki.freecad.org/images/FreeCAD-wordmark.svg"

freecad_icon_file: "/usr/share/icons/freecad.svg"
