# Instala soporte Flatpak si aún no existe.

- name: Instalar soporte flatpak
  apt:
    name: flatpak
    state: present
  when:
    - software_flatpak | length > 0




# Añade repositorio Flathub.
#
# Flathub es el repositorio principal utilizado
# por la mayoría de aplicaciones Flatpak.

- name: Añadir flathub
  flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
  when:
    - software_flatpak | length > 0


# Instala aplicaciones Flatpak definidas
# en los perfiles.

- name: Instalar flatpak
  community.general.flatpak:
    name: "{{ item }}"
    remote: flathub
    state: present
  loop: "{{ software_flatpak }}"
  when:
    - software_flatpak | length > 0
